-- MySQL Script generated by MySQL Workbench
-- 2017년 05월 23일 (화) 오후 03시 58분 52초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema shoppingmalldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shoppingmalldb` ;

-- -----------------------------------------------------
-- Schema shoppingmalldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingmalldb` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `shoppingmalldb` ;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`github_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`github_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`github_users` (
  `github_id` VARCHAR(32) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`github_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`users` (
  `user_id` VARCHAR(32) NOT NULL,
  `pw` VARCHAR(256) NOT NULL,
  `github_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_users_github_id`
    FOREIGN KEY (`github_id`)
    REFERENCES `shoppingmalldb`.`github_users` (`github_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_users_github_id` ON `shoppingmalldb`.`users` (`github_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`messages` (
  `user_id` VARCHAR(32) NOT NULL,
  `msg` VARCHAR(2048) NOT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_messages_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_messages_user_id` ON `shoppingmalldb`.`messages` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`orders` (
  `order_id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  `bank_account` VARCHAR(32) NOT NULL,
  `bank_pw` VARCHAR(32) NOT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_orders_user_id` ON `shoppingmalldb`.`orders` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`products` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `imgsrc` VARCHAR(200) NULL DEFAULT '/images/default.jpg',
  `serial_key` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`order_items` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`order_items` (
  `order_id` VARCHAR(64) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_num` INT(11) NOT NULL,
  CONSTRAINT `fk_order_item_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `shoppingmalldb`.`orders` (`order_id`),
  CONSTRAINT `fk_order_item_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `shoppingmalldb`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_order_item_product_id` ON `shoppingmalldb`.`order_items` (`product_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_order_item_order_id` ON `shoppingmalldb`.`order_items` (`order_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`shopping_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`shopping_cart` (
  `cart_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(30) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_num` INT(11) NOT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  CONSTRAINT `fk_shopping_cart_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `shoppingmalldb`.`products` (`product_id`),
  CONSTRAINT `fk_shopping_cart_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_shopping_cart_user_id` ON `shoppingmalldb`.`shopping_cart` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_shopping_cart_product_id` ON `shoppingmalldb`.`shopping_cart` (`product_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
