-- MySQL Script generated by MySQL Workbench
-- 2017년 05월 23일 (화) 오후 12시 17분 56초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shoppingmalldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shoppingmalldb` ;

-- -----------------------------------------------------
-- Schema shoppingmalldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingmalldb` DEFAULT CHARACTER SET latin1 ;
USE `shoppingmalldb` ;

-- -----------------------------------------------------
-- Table `shoppingmalldb`.`github_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`github_users` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`github_users` (
  `github_id` VARCHAR(32) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`github_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`users` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`users` (
  `user_id` VARCHAR(32) NOT NULL,
  `pw` VARCHAR(256) NOT NULL,
  `github_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_users_github_id`
    FOREIGN KEY (`github_id`)
    REFERENCES `shoppingmalldb`.`github_users` (`github_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`messages` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`messages` (
  `user_id` VARCHAR(32) NOT NULL,
  `msg` VARCHAR(2048) NOT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_messages_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`orders` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`orders` (
  `order_id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  `bank_account` VARCHAR(32) NULL DEFAULT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`products` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`products` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `imgsrc` VARCHAR(200) NULL DEFAULT '/images/default.jpg',
  `serial_key` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`order_items` (
  `order_id` VARCHAR(64) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_num` INT(11) NOT NULL,
  CONSTRAINT `fk_order_item_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `shoppingmalldb`.`orders` (`order_id`),
  CONSTRAINT `fk_order_item_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `shoppingmalldb`.`products` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `shoppingmalldb`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shoppingmalldb`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `shoppingmalldb`.`shopping_cart` (
  `cart_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(30) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `product_num` INT(11) NOT NULL,
  `added_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  CONSTRAINT `fk_shopping_cart_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `shoppingmalldb`.`products` (`product_id`),
  CONSTRAINT `fk_shopping_cart_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `shoppingmalldb`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO github_users ( github_id, email ) VALUES('alinghi', 'alinghi@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('asdfljh', 'cjdhlds08@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('bjgwak', 'bjgwak@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('blukat29', 'yunjong@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('DaramG', 'gksgudtjr456@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('dinggul', 'dinggul@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('donghwan17', 'prious@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('ggoboogy', 'jihyeon.yoon@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('Hyeongcheol-An', 'anh1026@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('ian0371', 'ian0371@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('jaemoon-sim', 'jettijam@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('james010kim', 'jangha@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('jcassou', 'jean.cassou-mounat@insa-lyon.fr');
INSERT INTO github_users ( github_id, email ) VALUES('jchoi2022', 'jschoi.2022@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('JeongOhKye', 'ohkye415@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('jhong3842', 'jhong3842@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('jmpark81', 'jmpark81@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('juanaevv', 'juanaevv@nate.com');
INSERT INTO github_users ( github_id, email ) VALUES('kaistgun', 'signal@kait.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('lbh0307', 'lbh0307@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('mfaerevaag', 'markus@faerevaag.no');
INSERT INTO github_users ( github_id, email ) VALUES('mickan921', 'jsoh921@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('mikkang', 'kmb1109@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('nohkwak', 'nhkwak@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('pr0v3rbs', 'pr0v3rbs@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('sbahn1992', 'sbahn1992@gmail.com');
INSERT INTO github_users ( github_id, email ) VALUES('seongil', 'su3604@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('seungwonwoo', 'seungwonwoo@kaist.ac.kr');
INSERT INTO github_users ( github_id, email ) VALUES('soomin-kim', 'soomink@kaist.ac.kr');

INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '5', 'ANCIENT CIVILIZATION', '/pics/ancient.png', 'ABCD-33DF-SFAF-F3AF');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '10', 'DIABLO MOUNTAIN', '/pics/diablo.png', 'KDGK-J2DF-AFIO-SSKG');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '1000000000', 'FLAG', '/pics/flag.png', '****-****-****-****');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '20', 'HORDE', '/pics/horde.png', 'BKEI-NS92-6DEH-DKFW');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '20', 'HYPER MARIO Bros', '/pics/hyper.png', 'NSDK-FLJS-IWSJ-FSKL');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '30', 'PLANET CRAFT', '/pics/planet.png', 'INGI-WOGN-DGKS-NJKG');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '30', 'THE RESTORANTS', '/pics/restorants.png', 'NZIR-NSKG-ISNG-IWPQ');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '50', 'SOCCER MANAGER 2022', '/pics/soccer.png', 'OWEU-NGKZ-GNBG-7LWN');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '50', 'HEROES OF SERGEONS', '/pics/stone.png', 'QNAM-ZIGN-IOPS-NXLO');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '10', 'KOREAN TRUCK SIMULATOR', '/pics/truck.png', 'Q9I4-H2MX-CFV9-82BA');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '10', 'PLANET CRAFT 2', '/pics/planet2.png', 'KGIG-NREI-382U-NBGW');
INSERT INTO products ( price, name, imgsrc, serial_key ) VALUES ( '5', 'REAL WATCH', '/pics/watch.png', 'KDNG-I023-874N-DS82');